language: node_js
before_install:
  - npm install -g grunt grunt-cli
before_script:
  - grunt coffee
node_js:
  - "0.10"
script:
  - grunt travis
after_script:
  - cat coverage/lcov.info | codeclimate
notifications:
  slack:
    masuilab:p4zvcihWTFLz1KwJXYGwJgeZ
addons:
  code_climate:
    repo_token:33e8f82a9ab973a223787487206a03312d98a161f07105793c293307c943b16d
